apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "epicrm.api.fullname" . }}
  labels:
    app: {{ include "epicrm.api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "epicrm.api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "epicrm.api.fullname" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Values.api.envFromSecret }}
          {{- if .Values.api.health.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.health.livenessProbe.path }}
              port: {{ .Values.api.health.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.api.health.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.health.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.api.health.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.health.readinessProbe.path }}
              port: {{ .Values.api.health.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.api.health.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.health.readinessProbe.periodSeconds }}
          {{- end }}
