apiVersion: v1
kind: Service
metadata:
  name: {{ include "epicrm.postgres.fullname" . }}
  labels:
    app: {{ include "epicrm.postgres.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "epicrm.postgres.fullname" . }}
