apiVersion: v1
kind: Service
metadata:
  name: {{ include "epic-crm.fullname" . }}-postgres
  labels:
    app: {{ include "epic-crm.name" . }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "epic-crm.name" . }}-postgres
