apiVersion: v1
kind: Service
metadata:
  name: {{ include "epic-crm.fullname" . }}-api
  labels:
    app: {{ include "epic-crm.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "epic-crm.name" . }}-api
